# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
